chances:
  kick-chance: 3000
  group-chance: 500
  crash-chance: 10000
  message-chance: 1000
  stinky-chance: 1000
  storm-chance: 5000
  prank-chance: 5000
betters:
  name-hider: true
  head-chat: true
  websocket:
    enabled: true
    server-control: true
random-messages:
  - "Пэрсик упал в черный квадрат Малевича."
  - "Я не щавель, я подорожник с размахом крыльев!"
  - "Съел бумеранг — возвращается обратно в желудок."
  - "Ты не твоя кредитка, а у неё лимит бесконечен."
  - "У меня морковный сок вместо крови, хочешь глоточек?"
  - "Каждый раз, когда ты засыпаешь, мыши подписывают новый договор с котом."
  - "Тап-тап-тап по крабу, а он улетел в космос."
  - "Почему носки? Потому что апельсин!"
  - "Каждый человек — это просто ходячая версия паровоза без рельсов."
  - "Съешь банан — получишь билет в страну лемуров."
  - "Почему я улыбаюсь? Да просто в кармане бегает хомяк на батарейках."
  - "Твой мозг танцует танго, пока ты смотришь в холодильник."
  - "Перец чили — это старший брат всех жгучих оскорблений."
  - "Когда ты последний раз обнимал кактус? Он скучает."
  - "Твой кот — это секретный агент под прикрытием сосиски."
  - "Я плыву по жизни, как ананас в компоте, и не парюсь."
  - "Креветка с топором — это не просто шутка, это стиль жизни."
  - "Почему все думают, что хлеб — это просто хлеб? Это философия."
  - "Вся твоя жизнь — это одна большая коробка с сюрпризом внутри."
  - "Когда у тебя плохой день, просто вспомни про бабушку, которая рэпит."
  - "Светофоры — это тайные сигнализаторы между мандаринами и апельсинами."
  - "Ты не видишь истину, потому что носишь очки с картофельным фильтром."
  - "Если тебя зовут, не отвечай, это может быть просто капуста."
  - "Я никогда не забуду тот день, когда карась предложил мне подработку."