kick-event-chance: 3000
group-event-chance: 500
crash-event-chance: 10000
message-event-chance: 1000
vova-event-chance: 1000
random-messages:
  - "Бабушка подключилась к Wi-Fi вселенной."
  - "Не пытайся обнять кактус."
  - "Почему холодильник разговаривает по-французски?"
  - "Кот научился программировать на языке уток."
  - "Гравитация — это просто очень упрямый ёжик."
  - "Чтобы найти смысл жизни, нужно спросить тапок."
  - "тап тап тап па хамяку..."
  - "Я слышу запах интернета в космосе."
  - "Чайник планирует революцию."
  - "Ответ — в носке за диваном."