kick-chance: 3000
group-chance: 500
crash-chance: 10000
message-chance: 1000
vova-chance: 1000
storm-chance: 5000
eschkere-chance: 5000
random-messages:
  - "Пэрсик упал в черный квадрат Малевича."
  - "Я не щавель, я подорожник с размахом крыльев!"
  - "Съел бумеранг — возвращается обратно в желудок."
  - "Ты не твоя кредитка, а у неё лимит бесконечен."
  - "У меня морковный сок вместо крови, хочешь глоточек?"
  - "Каждый раз, когда ты засыпаешь, мыши подписывают новый договор с котом."
  - "Тап-тап-тап по крабу, а он улетел в космос."
  - "Почему носки? Потому что апельсин!"
  - "Твой мозг — это запечённый батончик мюсли."
  - "Реальность — это всего лишь капля в океане бутербродов."
  - "Каждая моя ошибка — это ещё одна победа кота в боулинге."
  - "Бойцовский клуб — это когда ты играешь в шашки против своих тараканов."
  - "Не пытайся повторить, я сижу на невидимом троне из консервных банок."
  - "Когда-нибудь всё станет персиком, даже капуста."
  - "Вчера встретил talking pineapple на автовокзале."
  - "Твоя машина — это просто мандарин с колёсами, не обманывай себя."
  - "Когда я ем борщ, за мной наблюдают из параллельной вселенной."
  - "Хочешь поговорить о реальности? У меня морковь-заговорщица на кухне."
  - "Зачем стремиться к успеху, когда можно стремиться к шпинату?"
  - "Не доверяй мороженому, оно знает твои слабости."
  - "Я как капибара, но с лицом как у редьки."
  - "Почему бы не стать облаком и не уплыть в огород?"
  - "Каждый раз, когда ты смотришь на небо, где-то падает помидор."
  - "Мои мысли — это как стул из леденцов: красиво, но неудобно."
  - "Жизнь — это просто большая чашка с лапшой."
  - "Если ты забудешь своё имя, просто вспомни слово 'щавель'."
  - "У меня в голове всегда звучит саундтрек из мультика про арбуз."
  - "Котлеты любят, когда их гладят до состояния свинцовых гирь."
  - "Почему ты выбираешь воду, если есть фанта с гравитацией?"
  - "Твоя сила — это сила пяти тапков, осознай это."
  - "Всё, что ты знаешь о мире, — это просто яблоко в кармане."
  - "Если бы мишки управляли миром, мы бы купались в компоте."
  - "Я иду вперёд, как гусеница в носках."
  - "Моя тень всегда убегает, когда я достаю мармелад."
  - "Каждый человек — это просто ходячая версия паровоза без рельсов."
  - "Съешь банан — получишь билет в страну лемуров."
  - "Почему я улыбаюсь? Да просто в кармане бегает хомяк на батарейках."
  - "Твой мозг танцует танго, пока ты смотришь в холодильник."
  - "Перец чили — это старший брат всех жгучих оскорблений."
  - "Когда ты последний раз обнимал кактус? Он скучает."
  - "Твой кот — это секретный агент под прикрытием сосиски."
  - "Я плыву по жизни, как ананас в компоте, и не парюсь."
  - "Креветка с топором — это не просто шутка, это стиль жизни."
  - "Почему все думают, что хлеб — это просто хлеб? Это философия."
  - "Вся твоя жизнь — это одна большая коробка с сюрпризом внутри."
  - "Когда у тебя плохой день, просто вспомни про бабушку, которая рэпит."
  - "Светофоры — это тайные сигнализаторы между мандаринами и апельсинами."
  - "Ты не видишь истину, потому что носишь очки с картофельным фильтром."
  - "Если тебя зовут, не отвечай, это может быть просто капуста."
  - "Я никогда не забуду тот день, когда карась предложил мне подработку."