name: AbsolutelyRandom
version: 1.0-ALPHA
main: ru.dushkinmir.absolutlyRandom.AbsolutelyRandom
api-version: 1.21

permissions:
  absolutlyrandom.admin:
    description: Allows using debug commands for AbsolutelyRandomPlugin.
    default: op
