name: AbsolutelyRandom
version: 1.4.1-ALPHA
main: ru.dushkinmir.absolutelyRandom.AbsolutelyRandom
api-version: 1.21

permissions:
  absolutlyrandom.admin:
    description: Allows using debug commands for AbsolutelyRandomPlugin.
    default: op